### ISSUE TITLE
route66 is required as well for the SSE demo

### ISSUE THREAD

**Issue by hfmanson** [ignacio/lua_workshop_2013#1]
I installed it with
`sudo luarocks install http://github.com/ignacio/route66/raw/master/rockspecs/route66-scm-1.rockspec`
as described in https://github.com/ignacio/route66

luasec is required.

**Comment by ignacio** [comment]
Thank you. Added that to the readme.

luasec should not be required. LuaNode itself deals with the ssl stuff.
